### PR TITLE
Added Chief Delphi

### PR DESCRIPTION
**Pull request by C-MacD**

### CODE REVIEW

**Comment by felicianotech** [comment]
@C-MacD Hey, thank you for the contribution.

Would you be able to generate the details for this forum by running:

```bash
./bin/pull-data.sh src/content/communities/chiefdelphi.md
```

from the root of this repo? I think the only dependency needed is the `jq` command.

**Comment by C-MacD** [comment]
My apologies @felicianotech but I am not entirely sure how to do that.  Would you be able to walk me through it?  I am on Windows by the way.  I cloned the project to my computer.  When I tried to run the command in the root it wouldn't work.  Googling around told me that "./" and forward slashes are for Linux, not Windows.  I tried changing everything to backslashes but I couldn't get the command to run.

> I think the only dependency needed is the jq command.

I also don't understand what this means.

**Comment by felicianotech** [comment]
Oh okay. No worries, the pull-data script can't be run on Windows anyway. I'll run it for you.

Thank you for submitting a forum!

**Comment by felicianotech** [comment]
It's now live! https://www.discoursehub.com/communities/

**Comment by C-MacD** [comment]
Thank you!

**Pull request merged**
